version: '3'
services:

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "8545:8545"
    volumes:
      - ganache_data:/ganache_data
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.100
    healthcheck:
      test: wget  --header=Content-Type:application/json --post-data='{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://localhost:8545 -O /dev/null
      interval: 2s
      timeout: 5s
      retries: 30
    entrypoint:
      - node
      - ./ganache-core.docker.cli.js
      - -m
      - ${MNEMONIC}
      - --networkId
      - '1337'
      - --db=/ganache_data
      - --hostname
      - '0.0.0.0'
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "marketplace"
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.110 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d marketplace"]
      interval: 2s
      timeout: 50s
      retries: 25        
    ports:
      - 5432:5432

  marketplace_init:
    image: registry.videocoin.net/nft/marketplace:alpha-rc2
    container_name: marketplace_init
    depends_on:
      postgres:
        condition: service_healthy
    env_file: 
      - marketplace_env.list
    networks:
      vidnftnet:
    command:  bash -c 'sleep 10 && /goose -dir /migrations -table marketplace postgres "host=postgres port=5432 dbname=marketplace sslmode=disable" up'

  marketplace:
    image: registry.videocoin.net/nft/marketplace:alpha-rc2
    container_name: marketplace
    depends_on:
      marketplace_init:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file: 
      - marketplace_env.list
    #network_mode: host      
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.120 
    ports:
      - 8088:8088
          
  nft-app:
    image: registry.videocoin.net/nft/marketplace-ui:alpha-rc2
    container_name: nft-app 
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      REACT_APP_NETWORKS: ${REACT_APP_NETWORKS}
      REACT_APP_TOKEN_ADDRESS: ${REACT_APP_TOKEN_ADDRESS}
      REACT_APP_CUSTOM_PROVIDER_URL: ${REACT_APP_CUSTOM_PROVIDER_URL}
      REACT_APP_API_BASE_CUSTOM: ${REACT_APP_API_BASE_CUSTOM}
      REACT_APP_SITE_HOST_CUSTOM: ${REACT_APP_SITE_HOST_CUSTOM}
      
      # Wyvern contract addresses
      REACT_APP_WYVERN_EXCHANGE: ${REACT_APP_WYVERN_EXCHANGE}
      REACT_APP_WYVERN_PROXY_REGISTRY: ${REACT_APP_WYVERN_PROXY_REGISTRY}
      REACT_APP_WYVERN_ATOMICIZER: ${REACT_APP_WYVERN_ATOMICIZER}
      REACT_APP_WYVERN_TOKEN_TRANSFER_PROXY: ${REACT_APP_WYVERN_TOKEN_TRANSFER_PROXY}
      
      REACT_APP_WYVERN_DAO: ${REACT_APP_WYVERN_DAO} 
      REACT_APP_WYVERN_TOKEN: ${REACT_APP_WYVERN_TOKEN}
      REACT_APP_WYVERN_TOKEN: ${REACT_APP_WYVERN_TOKEN}
      REACT_APP_CUSTOM_FEE_RECIPIENT: ${REACT_APP_CUSTOM_FEE_RECIPIENT}
       
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.130 
    ports:
      - 8080:80

  nft-contracts-deploy:
    build: 
      context: videocoin-nft
    container_name: nft-contracts-deploy
    depends_on:
      ganache:
        condition: service_healthy
    env_file: 
      - nft-contracts_env.list
    volumes:
      - contracts_data:/code/data      
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.101
    command:  bash -c 'truffle --config truffle-config.js --network custom migrate && cat config.json'

  wyvern-contracts-deploy:
    build: 
      context: wyvern-ethereum
    container_name:  wyvern-contracts-deploy
    depends_on:
      ganache:
        condition: service_healthy
    env_file: 
      -  wyvern-contracts_env.list
    volumes:
      - contracts_data:/code/data      
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.102
    command:  bash -c 'truffle --config truffle.js --network custom migrate && cat config.json'

  explorer:
    hostname: explorer
    depends_on:
      - ganache
    image: alethio/ethereum-lite-explorer
    container_name: explorer
    ports:
      - 8090:80
    environment:
      APP_NODE_URL: "http://localhost:8545"
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.140 
    
networks:
  vidnftnet:
    driver: bridge
    ipam:
      config:
      - subnet: 173.26.0.0/24

volumes:
  ganache_data:
  contracts_data:
    

